#!/usr/bin/env node
/*
 * Generates a dot-matrix map of the UK & Ireland from Natural Earth land
 * geometry.
 *
 * Samples a uniform lat/lng grid over the British Isles, keeps the points
 * that fall on land (ray-casting point-in-polygon), and writes them as
 * normalised [u, v] coordinates in [0, 1] (equirectangular). The output is a
 * small JS module baked into the site so the page is fully self-contained at
 * runtime.
 */

const fs = require('fs');
const path = require('path');

const GEOJSON = path.join(__dirname, 'data', 'ne_110m_land.json');
const OUT = path.join(__dirname, '..', 'site', 'map-data.js');

// Grid resolution + crop. We sample a tight box around the British Isles so
// the silhouette of Great Britain and Ireland reads clearly as dots.
const STEP = 0.28;       // degrees between samples (fine — the area is small)
const LAT_MAX = 61.2;    // top of the sampled band (northern Scotland)
const LAT_MIN = 49.7;    // bottom (Channel coast)
const LNG_MIN = -11.2;   // west (Atlantic coast of Ireland)
const LNG_MAX = 2.2;     // east (East Anglia / Kent)

function loadPolygons() {
  const geo = JSON.parse(fs.readFileSync(GEOJSON, 'utf8'));
  const polys = []; // each: array of rings, ring[0] = outer
  for (const f of geo.features) {
    const g = f.geometry;
    if (g.type === 'Polygon') {
      polys.push(g.coordinates);
    } else if (g.type === 'MultiPolygon') {
      for (const p of g.coordinates) polys.push(p);
    }
  }
  return polys;
}

// Ray-casting against a single ring (array of [lng, lat]).
function inRing(lng, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1];
    const xj = ring[j][0], yj = ring[j][1];
    const intersect = (yi > lat) !== (yj > lat) &&
      lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

// Inside outer ring and outside every hole.
function onLand(lng, lat, polys) {
  for (const rings of polys) {
    if (inRing(lng, lat, rings[0])) {
      let inHole = false;
      for (let h = 1; h < rings.length; h++) {
        if (inRing(lng, lat, rings[h])) { inHole = true; break; }
      }
      if (!inHole) return true;
    }
  }
  return false;
}

function main() {
  const polys = loadPolygons();
  const dots = [];
  let row = 0;
  for (let lat = LAT_MAX; lat >= LAT_MIN; lat -= STEP, row++) {
    // Brick-offset alternating rows for a denser, organic dot texture.
    const offset = row % 2 ? STEP / 2 : 0;
    for (let lng = LNG_MIN + offset; lng < LNG_MAX; lng += STEP) {
      if (onLand(lng, lat, polys)) {
        const u = (lng + 180) / 360;
        const v = (90 - lat) / 180;
        dots.push([Math.round(u * 1e4) / 1e4, Math.round(v * 1e4) / 1e4]);
      }
    }
  }

  const header = `// Auto-generated by scripts/generate-map.js — do not edit by hand.\n` +
    `// ${dots.length} land dots, equirectangular [u,v] in [0,1].\n` +
    `// Sampled box: lat ${LAT_MIN}..${LAT_MAX}, lng ${LNG_MIN}..${LNG_MAX}, step ${STEP}°.\n`;
  const body = `window.COLY_MAP_DOTS = ${JSON.stringify(dots)};\n`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, header + body);
  console.log(`Wrote ${dots.length} dots -> ${path.relative(process.cwd(), OUT)} (${(header.length + body.length)} bytes)`);
}

main();
